import React from 'react';

const genRef=()=>{
    return [1,2,3].map(i=>React.createRef())
}

const cName="xc12 h-100"

const subCNameMinMax = ["xc1 h-100",
                        "xc3 h-100",
                        "xc8 h-100"]
  
const subCNameInput= subCNameMinMax

let partnerFilter=[
    //active
    { 
      templateType:"boolean",
      lb:"active",
      cName,  
      subCName:subCNameInput,    
      keyName:"active",
      refInput:genRef(),
      inputType:"checkbox",
      filterCommand:["active"]
    },
    { 
      templateType:"number",
      lb:"id",
      cName,  
      subCName:subCNameMinMax,
      keyName:"id",
      refInput:genRef(),
      inputType:"number",
      filterCommand:["id"]
    },
    //==============
    //title
    { 
      templateType:"selectObj",
      lb:"คำนำหน้า",
      cName,  
      subCName:subCNameInput,    
      keyName:"title",
      refInput:genRef(),
      inputType:"text",
      filterCommand:["title"],
      selectObj:"title"
    },
    //name
    { 
      templateType:"string",
      lb:"ชื่อ",
      cName,  
      subCName:subCNameInput,    
      keyName:"name",
      refInput:genRef(),
      inputType:"text",
      filterCommand:["name"]
    },
    //phone
    { 
      templateType:"arrayString",
      lb:"โทรศัพท์",
      cName,  
      subCName:subCNameInput,      
      keyName:"phone",
      refInput:genRef(),
      inputType:"text",
      filterCommand:["phone"]
    },
    //partnerType
    /*
    { 
      templateType:"selectObj",
      lb:"ประเภทคู่ค้า",
      cName,  
      subCName:subCNameInput,    
      keyName:"partnerType",
      refInput:genRef(),
      inputType:"text",
      filterCommand:["partnerType"],
      selectObj:"partnerType"
    },
    */
    //remark
    { 
      templateType:"string",
      lb:"หมายเหตุ",
      cName,  
      subCName:subCNameInput,    
      keyName:"remark",
      refInput:genRef(),
      inputType:"text",
      filterCommand:["remark"]
    },
    { 
      templateType:"number",
      lb:"แต้ม",
      cName,  
      subCName:subCNameMinMax,
      keyName:"remainingCustomerPoint",
      refInput:genRef(),
      inputType:"number",
      filterCommand:["remainingCustomerPoint"]
    },
    { 
      templateType:"number",
      lb:"ยอดใช้จ่าย",
      cName,  
      subCName:subCNameMinMax,
      keyName:"totalSpending",
      refInput:genRef(),
      inputType:"number",
      filterCommand:["totalSpending"]
    },
    //address:{number,tambon,district:province,postcode:},
    //address.number
    /*
    {       
      templateType:"arrayObjectString",
      lb:"ที่อยู่|เลขที่",
      cName,  
      subCName:subCNameInput,
      keyName:"address_number",
      refInput:genRef(),
      inputType:"text",
      filterCommand:["address","number"]
    },
    { 
      templateType:"arrayObjectString",
      lb:"ที่อยู่|ตำบล",
      cName,  
      subCName:subCNameInput,
      keyName:"address_tambon",
      refInput:genRef(),
      inputType:"text",
      filterCommand:["address","tambon"]
    },
    { 
      templateType:"arrayObjectString",
      lb:"ที่อยู่|อำเภอ",
      cName,  
      subCName:subCNameInput,
      keyName:"address_district",
      refInput:genRef(),
      inputType:"text",
      filterCommand:["address","district"]
    },
    { 
      templateType:"arrayObjectString",
      lb:"ที่อยู่|จังหวัด",
      cName,  
      subCName:subCNameInput,
      keyName:"address_province",
      refInput:genRef(),
      inputType:"text",
      filterCommand:["address","province"]
    },
    { 
      templateType:"arrayObjectString",
      lb:"ที่อยู่|รหัสไปรษณีย์",
      cName,  
      subCName:subCNameInput,
      keyName:"address_postcode",
      refInput:genRef(),
      inputType:"text",
      filterCommand:["address","postcode"]
    },   
    */
]

let productFilter=[
  //active
  { 
    templateType:"boolean",
    lb:"active",
    cName,  
    subCName:subCNameInput,    
    keyName:"active",
    refInput:genRef(),
    inputType:"checkbox",
    filterCommand:["active"]
  },
  //id
  { 
    templateType:"number",
    lb:"ไอดี",
    cName,  
    subCName:subCNameMinMax,
    keyName:"id",
    refInput:genRef(),
    inputType:"number",
    filterCommand:["id"]
  },
  //barcode
  { 
    templateType:"string",
    lb:"บาร์โค้ด",
    cName,  
    subCName:subCNameInput,    
    keyName:"barcode",
    refInput:genRef(),
    inputType:"text",
    filterCommand:["barcode"]
  },
  //name
  { 
    templateType:"string",
    lb:"ชื่อ",
    cName,  
    subCName:subCNameInput,    
    keyName:"productName",
    refInput:genRef(),
    inputType:"text",
    filterCommand:["productName"]
  },
  { 
    templateType:"boolean",
    lb:"เป็นวัตถุดิบ",
    cName,  
    subCName:subCNameInput,    
    keyName:"isRawMat",
    refInput:genRef(),
    inputType:"checkbox",
    filterCommand:["isRawMat"]
  },
  //groupId
  /*
  { 
    templateType:"number",
    lb:"ไอดีกลุ่ม",
    cName,  
    subCName:subCNameMinMax,
    keyName:"groupId",
    refInput:genRef(),
    inputType:"number",
    filterCommand:["groupId"]
  },
  //groupName
  { 
    templateType:"string",
    lb:"ชื่อกลุ่ม",
    cName,  
    subCName:subCNameMinMax,
    keyName:"groupName",
    refInput:genRef(),
    inputType:"text",
    filterCommand:["groupName"]
  },
  //unit
  { 
    templateType:"selectObj",
    lb:"หน่วย",
    cName,  
    subCName:subCNameInput,    
    keyName:"unit",
    refInput:genRef(),
    inputType:"text",
    filterCommand:["unit"],
    selectObj:"unit"
  },
  */
  //price
  { 
    templateType:"number",
    lb:"ราคา",
    cName,  
    subCName:subCNameInput,    
    keyName:"price",
    refInput:genRef(),
    inputType:"number",
    filterCommand:["price"]
  },
  //=================
 
  //stock

  { 
    templateType:"number",
    lb:"ยอดสต็อค",
    cName,  
    subCName:subCNameMinMax,
    keyName:"stock",
    refInput:genRef(),
    inputType:"number",
    filterCommand:["stock"]
  },
  //remark
    { 
      templateType:"string",
      lb:"หมายเหตุ",
      cName,  
      subCName:subCNameInput,    
      keyName:"remark",
      refInput:genRef(),
      inputType:"text",
      filterCommand:["remark"]
    },

]

//>............
//>>>>>>>>>>>>>>

let transactionFilter=[
    //active
    { 
      templateType:"boolean",
      lb:"active",
      cName,  
      subCName:subCNameInput,    
      keyName:"active",
      refInput:genRef(),
      inputType:"checkbox",
      filterCommand:["active"]
    },
  //id
  { 
    templateType:"number",
    lb:"id",
    cName,  
    subCName:subCNameMinMax,
    keyName:"id",
    refInput:genRef(),
    inputType:"number",
    filterCommand:["id"]
  },
  //date
  { 
    templateType:"number",
    lb:"วันที่",
    cName,  
    subCName:subCNameMinMax,
    keyName:"date",
    refInput:genRef(),
    inputType:"date",
    filterCommand:["date"]
  },
  
  //branchId
  /*
  { 
    templateType:"number",
    lb:"branchId",
    cName,  
    subCName:subCNameMinMax,
    keyName:"branchId",
    refInput:genRef(),
    inputType:"number",
    filterCommand:["branchId"]
  },
  */

  { 
    templateType:"selectArrayObj",
    lb:"ประเภทเอกสาร",
    cName,  
    subCName:subCNameInput,    
    keyName:"transactionType",
    refInput:genRef(),
    inputType:"text",
    filterCommand:["transactionType"],
    selectArrayObj:["transaction","transactionType"]
  },
  { 
    templateType:"selectObj",
    lb:"สถานะเอกสาร",
    cName,  
    subCName:subCNameInput,    
    keyName:"transactionStatus",
    refInput:genRef(),
    inputType:"text",
    filterCommand:["transactionStatus"],
    selectObj:"transactionStatus"
  },



  /*
  { 
    templateType:"selectObj",
    lb:"แอคทีฟ",
    cName,  
    subCName:subCNameInput,    
    keyName:"active",
    refInput:genRef(),
    inputType:"text",
    filterCommand:["active"],
    selectObj:"active"
  },
  */
  //partnerId
  
  { 
    templateType:"number",
    lb:"ไอดีคู่ค้า",
    cName,  
    subCName:subCNameMinMax,
    keyName:"partnerId",
    refInput:genRef(),
    inputType:"number",
    filterCommand:["partnerId"]
  },
  
  /*
  { 
    templateType:"selectObj",
    lb:"ประเภทคู่ค้า",
    cName,  
    subCName:subCNameMinMax,
    keyName:"partnerType",
    refInput:genRef(),
    inputType:"text",
    filterCommand:["partnerType"],
    selectObj:"partnerType"
  },
  */
  //title
  /*
  { 
    templateType:"selectObj",
    lb:"คำนำหน้า",
    cName,  
    subCName:subCNameInput,    
    keyName:"title",
    refInput:genRef(),
    inputType:"text",
    filterCommand:["title"],
    selectObj:"title"
  },
  */
  //name
  { 
    templateType:"string",
    lb:"ชื่อ",
    cName,  
    subCName:subCNameInput,    
    keyName:"name",
    refInput:genRef(),
    inputType:"text",
    filterCommand:["name"]
  },
  //phone
  { 
    templateType:"arrayString",
    lb:"โทรศัพท์",
    cName,  
    subCName:subCNameInput,      
    keyName:"phone",
    refInput:genRef(),
    inputType:"text",
    filterCommand:["phone"]
  },
  { 
    templateType:"selectObj",
    lb:"สถานะโต๊ะ",
    cName,  
    subCName:subCNameInput,    
    keyName:"tableStatus",
    refInput:genRef(),
    inputType:"text",
    filterCommand:["tableStatus"],
    selectObj:"tableStatus"
  },
  { 
    templateType:"selectObj",
    lb:"สถานะคิว",
    cName,  
    subCName:subCNameInput,    
    keyName:"queueStatus",
    refInput:genRef(),
    inputType:"text",
    filterCommand:["queueStatus"],
    selectObj:"queueStatus"
  },
]




const stickerFilter=[

  //id
  { 
    templateType:"number",
    lb:"id",
    cName,  
    subCName:subCNameMinMax,
    keyName:"id",
    refInput:genRef(),
    inputType:"number",
    filterCommand:["id"]
  },
  //date
  { 
    templateType:"date",
    lb:"วันที่",
    cName,  
    subCName:subCNameMinMax,
    keyName:"date",
    refInput:genRef(),
    inputType:"date",
    filterCommand:["date"]
  },

    //recordName
    { 
      templateType:"string",
      lb:"ชื่อรายการ",
      cName,  
      subCName:subCNameInput,    
      keyName:"recordName",
      refInput:genRef(),
      inputType:"text",
      filterCommand:["recordName"]
    },

    //recordBy
    { 
      templateType:"string",
      lb:"ผู้บันทึก",
      cName,  
      subCName:subCNameInput,    
      keyName:"recordBy",
      refInput:genRef(),
      inputType:"text",
      filterCommand:["recordBy"]
    },

    {       
      templateType:"arrayObjectString",
      lb:"สินค้า|บาร์โค้ด",
      cName,  
      subCName:subCNameInput,
      keyName:"productData_code",
      refInput:genRef(),
      inputType:"text",
      filterCommand:["productData","code"]
    },
    { 
      templateType:"arrayObjectString",
      lb:"สินค้า|ชื่อสินค้า",
      cName,  
      subCName:subCNameInput,
      keyName:"productData_name",
      refInput:genRef(),
      inputType:"text",
      filterCommand:["productData","name"]
    },

]


const billMenuFilter=[
  { 
    templateType:"boolean",
    lb:"active",
    cName,  
    subCName:subCNameInput,    
    keyName:"active",
    refInput:genRef(),
    inputType:"checkbox",
    filterCommand:["active"]
  },
  //id
  { 
    templateType:"number",
    lb:"ไอดี",
    cName,  
    subCName:subCNameMinMax,
    keyName:"id",
    refInput:genRef(),
    inputType:"number",
    filterCommand:["id"]
  },
  //date
  { 
    templateType:"number",
    lb:"วันที่",
    cName,  
    subCName:subCNameMinMax,
    keyName:"date",
    refInput:genRef(),
    inputType:"date",
    filterCommand:["date"]
  },
  //transactionType
  { 
    templateType:"selectArrayObj",
    lb:"ประเภทเอกสาร",
    cName,  
    subCName:subCNameInput,    
    keyName:"transactionType",
    refInput:genRef(),
    inputType:"text",
    filterCommand:["transactionType"],
    selectArrayObj:["transaction","transactionType"]
  },
  //tableStatus
  { 
    templateType:"selectObj",
    lb:"สถานะโต๊ะ",
    cName,  
    subCName:subCNameInput,    
    keyName:"tableStatus",
    refInput:genRef(),
    inputType:"text",
    filterCommand:["tableStatus"],
    selectObj:"tableStatus"
  },
]


const StateTemplate={
    partnerFilter,productFilter,transactionFilter,
    stickerFilter,billMenuFilter
}
  
export default StateTemplate
  